version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tiba-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tiba_todos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - tiba-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: tiba-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - tiba-network

  backend-service:
    build:
      context: .
      dockerfile: backend_service/Dockerfile
    container_name: tiba-backend
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - POSTGRES_CONNECTION_STRING=Host=postgres;Database=tiba_todos;Username=postgres;Password=postgres
    restart: unless-stopped
    networks:
      - tiba-network

  rest-service:
    build:
      context: .
      dockerfile: rest_service/Dockerfile
    container_name: tiba-rest
    ports:
      - "5000:8080"   # Map host port 5000 to container port 8080
    depends_on:
      - backend-service
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - JWT_VALIDATE_ISSUER=false
      - JWT_VALIDATE_AUDIENCE=false
      - JWT_VALIDATE_LIFETIME=false
      - JWT_VALIDATE_ISSUER_SIGNING_KEY=false
      - JWT_REQUIRE_EXPIRATION_TIME=false
    restart: unless-stopped
    networks:
      - tiba-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  tiba-network:
    driver: bridge